project_id = "ldlytdqspngpvfwtpula"

[auth]
enabled = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.admin-actions]
verify_jwt = true

[functions.create-cinetpay-payment]
verify_jwt = true

[functions.verify-cinetpay-payment]
verify_jwt = false