-- Insert demo sponsored listings
INSERT INTO public.listings (
  title, 
  price, 
  city, 
  country_code, 
  lat, 
  lng, 
  description,
  status,
  is_sponsored,
  sponsored_until,
  sponsor_amount,
  sponsored_at
) VALUES 
(
  'Villa Moderne de Luxe - Cocody',
  85000000,
  'Abidjan',
  'CI',
  5.3478,
  -4.0267,
  'Magnifique villa moderne avec piscine, jardin paysager et garage pour 3 voitures. Quartier résidentiel sécurisé.',
  'published',
  true,
  (now() + interval '30 days'),
  120,
  now()
),
(
  'Appartement Haut Standing - Plateau',
  45000000,
  'Abidjan',
  'CI',
  5.3197,
  -4.0267,
  'Appartement de standing avec vue panoramique sur la lagune. Immeuble sécurisé 24h/24 avec ascenseur.',
  'published',
  true,
  (now() + interval '15 days'),
  65,
  now()
),
(
  'Terrain Titre Foncier - Bingerville',
  25000000,
  'Bingerville',
  'CI',
  5.3550,
  -3.8950,
  'Terrain de 500m² avec titre foncier définitif. Idéal pour construction villa. Quartier en plein développement.',
  'published',
  true,
  (now() + interval '7 days'),
  35,
  now()
),
(
  'Villa Familiale avec Piscine - Riviera',
  120000000,
  'Abidjan',
  'CI',
  5.3728,
  -3.9731,
  'Spacieuse villa familiale avec 5 chambres, piscine olympique et terrain de tennis. Sécurité 24h.',
  'published',
  true,
  (now() + interval '30 days'),
  120,
  now()
),
(
  'Duplex Moderne - Marcory',
  65000000,
  'Abidjan',
  'CI',
  5.2858,
  -3.9731,
  'Magnifique duplex avec terrasse panoramique. Finitions haut de gamme et parking privé.',
  'published',
  true,
  (now() + interval '15 days'),
  65,
  now()
);