// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldlytdqspngpvfwtpula.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkbHl0ZHFzcG5ncHZmd3RwdWxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTI0OTgsImV4cCI6MjA3MzMyODQ5OH0.kRFHyTxS1Ter_N2eZxQUo1RU7DmZCnmwkkjU_5KpcVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});